# Övning 6 Geodetic astronomy 

In [51]:
from methods_AG1817 import *

# Problem 6.1

    On March 1, 1981, UT1 = 0h the Equation of the Equinox (Eq:E) is -0.8s. compute for this epoch:




---
a. JD
$$ M > 2: y = Y = 1981, m = M = 3 \\
JD = int(365.25 * Y) + int(30.6001 * (M + 1)) + D + UT1 / 24 + 1720981.5 $$


In [52]:
y = Y = 1981
m = M = 3
D = 1
UT1 = 0.0

JD = int(365.25 * Y) + int(30.6001 * (M + 1)) + D + UT1 / 24 + 1720981.5
print("JD = ", JD, "Days")

JD =  2444664.5 Days


---
b. T0
$$ T_0 = \frac{JD_{UT=0} - 2451545}{36525} $$


In [53]:
T_0 = (JD - 2451545) / 36525
print("T_0 = ", T_0)

T_0 =  -0.18837782340862422


---

c. (GMST)0
$$ (GMST)_0 = 24110.54841^s + 8640184.812866^s * T_0 + 0.093104^s * T_0^2 - 6.2^s * 10^{-6} * T_0^3 \\$$ 


In [54]:
GMST_0 = 24110.54841 + 8640184.812866 * T_0 + 0.093104 * T_0 ** 2 - 6.2 * 10 ** -6 * T_0 ** 3
while GMST_0 < 0:
    GMST_0 += 3600 * 24
GMST_0_hours, GMST_0_minutes, GMST_0_seconds = convert_to_hours_minutes_seconds(GMST_0)
print("GMST_0 = ", GMST_0_hours, "h", GMST_0_minutes, "m", GMST_0_seconds, "s")

GMST_0 =  10 h 34 m 51.342818000819534 s



    convert to hours, minutes and seconds:  
$$ 
hours = int(time / 3600) \\
minutes = int((time - (hours * 3600)) / 60) \\
seconds = time - (hours * 3600) - (minutes * 60) \\
$$


In [55]:
GMST_0_hours, GMST_0_minutes, GMST_0_seconds = convert_to_hours_minutes_seconds(GMST_0)
print("GMST_0 ≈ ", GMST_0_hours, "h", GMST_0_minutes, "m", round(GMST_0_seconds, 4), "s")

GMST_0 ≈  10 h 34 m 51.3428 s


---

d. GAST when $SNT = 22^h 50^m 42.0^s$ at the same day (SNT = Swedish standard time)

$$ 
SNT_{UT1} = SNT - 1^h \\
GMST = (GMST)_0 + 1.00273790935 * SNT_{UT1} \\
GAST = GMST + Eq.E
$$



In [56]:
Eq_E = -0.8

SNT = 22.0 + 50.0 / 60 + 42.0 / 3600
SNT_UT1 = (SNT - 1) * 3600
print("SNT_UT1 = ", SNT_UT1, "s")
GMST = GMST_0 + SNT_UT1 * 1.00273790935
print("GMST = ", GMST, "s")
GAST = GMST + Eq_E
print("GAST = ", GAST, "s")
GAST_hours, GAST_minutes, GAST_seconds = convert_to_hours_minutes_seconds(GAST)
if GAST_hours > 24:
    GAST_hours -= 24
print("GAST ≈ ", GAST_hours, "h", GAST_minutes, "m", round(GAST_seconds, 4), "s")


SNT_UT1 =  78642.0 s
GMST =  116948.65748510351 s
GAST =  116947.85748510351 s
GAST ≈  8 h 29 m 7.8575 s


# Problem 6.2

At the official Swedish time $SNT = 22^h 50^m 42.0^s$ on March 1, 1981, a star was observed in the South of the local meridian from a ground station. The equatorial coordinates of the star are as follows:

$$ \delta = 51\degree 1' 14'',  \alpha = 9^h 38^m 11.1^s $$

The height angle of the star has been measued to $h = 80\degree 25' 34'$. Find out the astronomical latitude
($\phi$) and longitude ($\lambda$) of this observation station. (Hints: use results from **Problem 7.1**)

---
    Calculations:
$$
Z = 90\degree - h \\
\Lambda = LAST - GAST = \alpha - GAST \\
\Phi = \delta + z \\
$$

In [57]:
print("GAST = ", GAST, "s")
delta = 51 + 1 / 60 + 14 / 3600
print("δ = ", delta, "°")
alpha = (9 + 38 / 60 + 11.1 / 3600) * 3600
print("α = ", alpha, "s")
h = 80 + 25 / 60 + 34 / 3600
print("h = ", h, "°")

z = 90 - h
print("z = ", z, "°")
λ = alpha - GAST
while λ < 0:
    λ += 3600 * 24
print("\n", "λ = ", λ, "s")
λ_hour, λ_min, λ_sec = convert_to_hours_minutes_seconds(λ)
print("λ ≈ ", λ_hour, "h", λ_min, "m", λ_sec, "s")

φ = delta + z
print("\n", "φ = ", φ, "°")

φ = convert_to_degrees_minutes_seconds(φ)
print("φ ≈ ", φ[0], "°", φ[1], "'", round(φ[2], 4), "''")


GAST =  116947.85748510351 s
δ =  51.02055555555555 °
α =  34691.1 s
h =  80.42611111111111 °
z =  9.573888888888888 °

 λ =  4143.242514896498 s
λ ≈  1 h 9 m 3.242514896497596 s

 φ =  60.59444444444444 °
φ ≈  60 ° 35 ' 40.0 ''


# Problem 6.3

**Assume that at a point A, the geocentric coordinates referred to the instantaneous pole of the earth has been determined to (unit: metres) :**

$$
X = 3 042 053.735 \\
Y = 988 423.176 \\
Z = 5 503 075.210 \\
$$

**The polar position at the time of coordinates determination is :**

$$
x_p = +012" \\
y_p = +0.15" $$

**The gravity value at A is $g = 9.78 m/s^2$ and GRS-80 reference ellipsoid will be used.**



---

a) compute the geocentric coordinates of A referred to the CIO pole ;

$$
R_p = 
\begin{bmatrix}
\cos(x_p) & \sin(x_p)\sin(y_p) & \sin(x_p)\cos(y_p) \\
0 & \cos(y_p) & -\sin(y_p) \\
-\sin(x_p) & \cos(x_p)\sin(y_p) & \cos(x_p)\cos(y_p) \\
\end{bmatrix} 
$$

$$
\begin{bmatrix}
x_0 \\
y_0 \\
z_0 \\
\end{bmatrix} 
= R_p 
\begin{bmatrix}
x \\
y \\
z \\
\end{bmatrix}
$$


In [58]:


x_p = (0.12 / 3600) * np.pi / 180
y_p = (0.15 / 3600) * np.pi / 180
X = 3042053.735
Y = 988423.176
Z = 5503075.210

Rp = np.array([
    [np.cos(x_p), np.sin(x_p) * np.sin(y_p), np.sin(x_p) * np.cos(y_p)],
    [0, np.cos(y_p), -np.sin(y_p)],
    [-np.sin(x_p), np.cos(x_p) * np.sin(y_p), np.cos(x_p) * np.cos(y_p)]
])

[[x_0], [y_0], [z_0]] = np.dot(Rp, np.array([[X], [Y], [Z]]))
print("x_0 = ", round(x_0, 9), "m")
print("y_0 = ", round(y_0, 9), "m")
print("z_0 = ", round(z_0, 9), "m")


x_0 =  3042056.936559284 m
y_0 =  988419.174050514 m
z_0 =  5503074.159004108 m


---
b) estimate the changes in the latitude and longitude of A when the CIO pole is used 

$$
\delta\phi = -(x_p\cos{\lambda} - y_p\sin{\lambda}) \\
\delta\lambda = -(x_p\sin{\lambda} - y_p\cos{\lambda})\tan{\phi} \\
$$


In [59]:
latitude, longitude, height = geocentric_to_geodetic(GRS80, x_0, y_0, z_0, height_0=0)
latitude, longitude = np.radians(latitude), np.radians(longitude)

delta_latitude = np.degrees(-(x_p * np.cos(longitude) - y_p * np.sin(longitude)))
delta_longitude = np.degrees(-(x_p * np.sin(longitude) + y_p * np.cos(longitude)) * np.tan(latitude))

print("Δφ = ", round(delta_latitude * 3600, 5), "''")
print("Δλ = ", round(delta_longitude * 3600, 5), "''")


Δφ =  -0.06777 ''
Δλ =  -0.31132 ''


---
c) compute the geocentric latitude  at A and thereafter the potential change due to the polar motion;
$$
\overline{\phi} = \arctan\left(\frac{z}{\sqrt{x^2 + y^2}}\right) \\
r = \sqrt{x^2 + y^2 + z^2} \\
\delta\Omega = -\frac{1}{2}w^2r^2\sin{2\overline{\phi}} * \delta\overline{\phi} \\
w = 0.72921151*10^{-4} s^{-1} \quad (kompendium \ s.222)
$$

In [60]:
r = np.sqrt(x_0 ** 2 + y_0 ** 2 + z_0 ** 2)
w = 0.72921151 * 10 ** -4

latitude_roof = np.arctan(z_0 / np.sqrt(x_0 ** 2 + y_0 ** 2))
print("φ' = ", np.degrees(latitude_roof), "°")
latitude_roof_temp = convert_to_degrees_minutes_seconds(np.degrees(latitude_roof))
print("φ' ≈ ", latitude_roof_temp[0], "°", latitude_roof_temp[1], "'", round(latitude_roof_temp[2], 3), "''")

delta_Omega = -0.5 * w ** 2 * r ** 2 * np.sin(2 * latitude_roof) * np.radians(delta_latitude)
print("ΔΩ = ", round(delta_Omega, 4), "m^2/s^2")

φ' =  59.83313600011295 °
φ' ≈  59 ° 49 ' 59.29 ''
ΔΩ =  0.0308 m^2/s^2


---
d) Find out the surface gravity change at A due to the polar motion ;
$$
\delta g_p = \frac{\delta\delta\omega}{\delta r} = w^2r\sin{2\overline{\phi}} * \delta\overline{\phi}
$$


In [61]:
delta_g_p = w ** 2 * r * np.sin(2 * latitude_roof) * np.radians(delta_latitude)
print("Δg' = ", delta_g_p, "m/s^2")

Δg' =  -9.663555980302746e-09 m/s^2


---
e) how much will the sea level near A change due to the polar motion ?
$$
\delta N_p = \frac{\delta\omega}{g}
$$



In [62]:
g = 9.78
delta_N_p = delta_Omega / g
print("ΔNp' = ", delta_N_p, "m")

ΔNp' =  0.0031446733868475104 m


# Problem 6.4

**On February 20, 2001**, at $t = 15^h 15^m$ (Swedish standard time), the Earth orientation parameters have the following values:
$$ 
\Delta\epsilon = -1.707" \\
\Delta\psi = -15.447" \\
x_p = -0.0466" \\
y_p = +0.4391 \\
dUT1 = UT1 - UTC = 0,0471^s
$$

In the International Celestial Reference Frame referred to the mean equator and equinox at J2000.0, an artificial satellite has the following geocentric coordinates:

$$
\begin{bmatrix}
X \\
Y \\
Z \\
\end{bmatrix}_{ICRF}
= 
\begin{bmatrix}
12 791 872.0418 \\
4 173 410.3284 \\
22 669 864.5407 \\
\end{bmatrix}metre
$$

Transform the above coordinates in the ICRF to coordinates in the ITRF by the following steps:


In [63]:
delta_epsilon = -1.707  # Sekunder
delta_psi = -15.447  # Sekunder
x_p = -0.0466  # Sekunder
y_p = 0.4391  # Sekunder
dUT1 = 0.0471  # Sekunder
UTC = (14 + 15 / 60) * 3600  # Sekunder

X, Y, Z = 12791872.0418, 4173410.3284, 22669864.5407  #Meter

---
a. computer the Julian date $(JD_0)$ and Julian Century $(T_0)$ for $UT1 = 0$
$$
y = 2001 - 1 \\
M = 2 + 12 \\
JD_0 = INT(365.25 * y) + INT(30.6001 * (M + 1)) + D + 1720981.5 \\
T_0 = \frac{JD_0-J2000}{36525} \\
$$



In [64]:
y = 2001 - 1
M = 2 + 12
D = 20
J2000 = 2451545.0
JD_0 = int(365.25 * y) + int(30.6001 * (M + 1)) + D + 1720981.5
print("JD_0 = ", JD_0)
T_0 = (JD_0 - J2000) / 36525
print("T_0 = ", T_0)


JD_0 =  2451960.5
T_0 =  0.01137577002053388


---
b. compute $UT1$, the Julian date $(JD)$ and Julian Century $(T)$ for epoch $t = 15^h 15^m$
$$
y = 2001 - 1 \\
M = 2 + 12 \\
UT1 = UTC + dUT1 \\
J2000 = 2451545.0 \\
JD = INT(365.25 * y) + INT(30.6001 * (M + 1)) + D + \frac{UT1}{24} + 1720981.5 \\
T = \frac{JD-J2000}{36525}\\
$$

In [65]:
UT1 = (dUT1 + UTC) / 3600
J2000 = 2451545.0
print("UT1 = ", UT1, "h")
JD = int(365.25 * y) + int(30.6001 * (M + 1)) + D + (UT1 / 24) + 1720981.5
print("JD = ", JD, "Days")
T = (JD - J2000) / 36525
print("T = ", T)

UT1 =  14.250013083333334 h
JD =  2451961.0937505453 Days
T =  0.011392026024511687


---
c. compute the precession parameters $\xi, z, \theta$ and the precession matrix P (Check if P is orthogonal: $PP^T = P^TP = I$)

$$
\xi = 2306.2181 * T + 0.30188 * T^2 + 0.017998 * T^3 * \frac{1}{3600} * \frac{\pi}{180}\\
z = 2306.2181 * T + 1.09468 * T^2 + 0.018203 * T^3 * \frac{1}{3600} * \frac{\pi}{180}\\
\theta = 2004.3109 * T - 0.42665 * T^2 - 0.041833 * T^3 * \frac{1}{3600} * \frac{\pi}{180}\\
$$

$$
P(z, \theta, \xi) = 
\begin{bmatrix}
+\cos{z}\cos{\theta}\cos{\xi}-\sin{z}\sin{\xi} & -\cos{z}\cos{\theta}\sin{\xi}-\sin{z}\cos{\xi} & -\cos{z}\sin{\theta} \\
+\sin{z}\cos{\theta}\cos{\xi}+\cos{z}\sin{\xi} & -\sin{z}\cos{\theta}\sin{\xi}+\cos{z}\cos{\xi} & -\sin{z}\sin{\theta} \\
+\sin{\theta}\cos{\xi} & -\sin{\theta}\sin{\xi} & +\cos{\theta} \\
\end{bmatrix} 
$$

In [66]:

xi = np.radians((2306.2181 * T + 0.30188 * T ** 2 + 0.017998 * T ** 3) / 3600)
print("ξ = ", xi, "rad")
z = np.radians((2306.2181 * T + 1.09468 * T ** 2 + 0.018203 * T ** 3) / 3600)
print("z = ", z, "rad")
theta = np.radians((2004.3109 * T - 0.42665 * T ** 2 - 0.041833 * T ** 3) / 3600)
print("θ = ", theta, "rad")

P = np.array(
    [[np.cos(z) * np.cos(theta) * np.cos(xi) - np.sin(z) * np.sin(xi),
      -np.cos(z) * np.cos(theta) * np.sin(xi) - np.sin(z) * np.cos(xi),
      -np.cos(z) * np.sin(theta)],
     [np.sin(z) * np.cos(theta) * np.cos(xi) + np.cos(z) * np.sin(xi),
      -np.sin(z) * np.cos(theta) * np.sin(xi) + np.cos(z) * np.cos(xi),
      -np.sin(z) * np.sin(theta)],
     [+np.sin(theta) * np.cos(xi), -np.sin(theta) * np.sin(xi), np.cos(theta)]])
print("P = ", P)
PPT = np.dot(P, P.T)
PTP = np.dot(P.T, P)

if np.allclose(PPT, np.eye(3)) and np.allclose(PTP, np.eye(3)):
    print("Matrix P is orthogonal.")
else:
    print("Matrix P is not orthogonal.")



ξ =  0.00012737284801749287 rad
z =  0.00012737334683504228 rad
θ =  0.00011069802414532401 rad
P =  [[ 9.99999961e-01 -2.54746191e-04 -1.10698023e-04]
 [ 2.54746191e-04  9.99999968e-01 -1.40999778e-08]
 [ 1.10698023e-04 -1.40999225e-08  9.99999994e-01]]
Matrix P is orthogonal.



---
d. compute the mean obliquity of the ecliptic ("0), the true obliquity of the ecliptic $(\epsilon = \epsilon_0 + \Delta\epsilon)$ and the nutation matrix $N(\epsilon_0,\Delta\epsilon, \Delta\psi)$.(Check if $N$ is orthogonal)
$$
\epsilon_0 = (23\degree 26' 21.448'' - 46.8150'' * T - 0.00059'' * T^2 + 0.001813'' * T^3) * \frac{\pi}{180}  \\
\epsilon = (\epsilon_0 + \Delta\epsilon)  * \frac{\pi}{180} \\

N(\epsilon_0, \Delta\epsilon, \Delta\psi) = 
\begin{bmatrix}
\cos{\Delta\psi} & -\sin{\Delta\psi}\cos{\epsilon_0} & -\sin{\Delta\psi}\sin{\epsilon_0} \\
+\sin{\Delta\psi}\cos{\epsilon} & +\cos{\Delta\psi}\cos{\epsilon}\cos{\epsilon_0} + \sin{\epsilon}\sin{\epsilon_0} & +\cos{\Delta\psi}\cos{\epsilon}\sin{\epsilon_0} - \sin{\epsilon}\cos{\epsilon_0} \\
+\sin{\Delta\psi}\sin{\epsilon} & +\cos{\Delta\psi}\sin{\epsilon}\cos{\epsilon_0} - \cos{\epsilon}\sin{\epsilon_0} & +\cos{\Delta\psi}\sin{\epsilon}\sin{\epsilon_0} + \cos{\epsilon}\cos{\epsilon_0} \\
\end{bmatrix} 
$$

In [67]:
delta_epsilon = np.radians(delta_epsilon) / 3600
delta_psi = np.radians(delta_psi / 3600)
print("Δε = ", delta_epsilon, "rad")
print("Δψ = ", delta_psi, "h")

epsilon_0 = np.radians(
    23 + 26 / 60 + 21.448 / 3600 - 46.8150 / 3600 * T - 0.00059 / 3600 * T ** 2 + 0.001813 / 3600 * T ** 3)
print("ε_0 = ", epsilon_0, "rad")
epsilon = epsilon_0 + delta_epsilon
print("ε = ", epsilon, "rad")

N = np.array([[np.cos(delta_psi), -np.sin(delta_psi) * np.cos(epsilon_0), -np.sin(delta_psi) * np.sin(epsilon_0)],
              [np.sin(delta_psi) * np.cos(epsilon),
               np.cos(delta_psi) * np.cos(epsilon) * np.cos(epsilon_0) + np.sin(epsilon) * np.sin(epsilon_0),
               np.cos(delta_psi) * np.cos(epsilon) * np.sin(epsilon_0) - np.sin(epsilon) * np.cos(epsilon_0)],
              [np.sin(delta_psi) * np.sin(epsilon),
               np.cos(delta_psi) * np.sin(epsilon) * np.cos(epsilon_0) - np.cos(epsilon) * np.sin(epsilon_0),
               np.cos(delta_psi) * np.sin(epsilon) * np.sin(epsilon_0) + np.cos(epsilon) * np.cos(epsilon_0)]])
print("N = ", N)

NNT = np.dot(N, N.T)
NTN = np.dot(N.T, N)

if np.allclose(NNT, np.eye(3)) and np.allclose(NTN, np.eye(3)):
    print("Matrix N is orthogonal.")
else:
    print("Matrix N is not orthogonal.")


Δε =  -8.27576953653978e-06 rad
Δψ =  -7.488916932099002e-05 h
ε_0 =  0.4090902186248054 rad
ε =  0.40908194285526883 rad
N =  [[ 9.99999997e-01  6.87095465e-05  2.97890231e-05]
 [-6.87097930e-05  9.99999998e-01  8.27474614e-06]
 [-2.97884545e-05 -8.27679291e-06  1.00000000e+00]]
Matrix N is orthogonal.


---

e. compute $(GMST)_0, GMST, GAST$ for epoch $t$. (Hints: to compute GMST, one need
to use the Julian century T0 computed in (a)
$$
(GMST)_0 = 24110.54841^s + 8640184.812866^s * T_0 + 0.093104^s * T_0^2 - 6.2^s * 10^{-6} * T_0^3 \\
GMST = (GMST)_0 + 1.00273790935 * UT1 \\
GAST = GMST + \Delta\psi\cos{\epsilon_0} \\ 
\Delta\psi\text{ is in arcseconds, convert to seconds by dividing by 15} \\
$$

In [68]:
GMST_0 = (24110.54841 + 8640184.812866 * T_0 + 0.093104 * T_0 ** 2 - 6.2 * 10 ** -6 * T_0 ** 3) / 3600
print("\n", "GMST_0 = ", GMST_0, "h")

GMST = GMST_0 + (UT1 * 1.00273790935)
while GMST >24:
    GMST -= 24
print("\n", "GMST = ", GMST, "h")
GAST = GMST + (np.degrees(delta_psi) / 15) * np.cos(epsilon_0)

while GAST > 24:
    GAST -= 24
print("\n", "GAST = ", GAST, "h")



 GMST_0 =  33.99980660781155 h

 GMST =  0.28883493520336145 h

 GAST =  0.28857248406817915 h



---
f. compute the rotation matrix $R_3(GAST)$, the polar motion matrix $R_p(x_p,y_p)$ and the joint rotation matrix $R = R_p * R_3 * N * P$ used for transformation from $ICRS$ to $ITRF$: Check if $R_2, R_p$ and $R$ are orthogonal).
$$
R_3(GAST) = 
\begin{bmatrix}
\cos{GAST} & \sin{GAST} & 0 \\
-\sin{GAST} & \cos{GAST} & 0 \\
0 & 0 & 1 \\
\end{bmatrix} \\

R * R^T ≈ I \\

R_p = 
\begin{bmatrix}
\cos(x_p) & \sin(x_p)\sin(y_p) & \sin(x_p)\cos(y_p) \\
0 & \cos(y_p) & -\sin(y_p) \\
-\sin(x_p) & \cos(x_p)\sin(y_p) & \cos(x_p)\cos(y_p) \\
\end{bmatrix}  \\

R_p * R_p^T ≈ I \\

R = R_p * R_3 * N * P \\

R * R^T ≈ I \\

$$

In [69]:
GAST = np.radians(GAST) * 15

x_p = np.radians(x_p) / 3600
y_p = np.radians(y_p) / 3600
print("GAST = ", GAST, "rad")
print("x_p = ", x_p, "rad")
print("y_p = ", y_p, "rad")

R_3 = np.array([[np.cos(GAST), np.sin(GAST), 0], [-np.sin(GAST), np.cos(GAST), 0], [0, 0, 1]])
print("\n", "R_3 = ", R_3)
R_3R_3T = np.dot(R_3, R_3.T)
R_3TR_3 = np.dot(R_3.T, R_3)
if np.allclose(R_3R_3T, np.eye(3)) and np.allclose(R_3TR_3, np.eye(3)):
    print("Matrix R_3 is orthogonal.")
else:
    print("Matrix R_3 is not orthogonal.")

Rp = np.array([
    [np.cos(x_p), np.sin(x_p) * np.sin(y_p), np.sin(x_p) * np.cos(y_p)],
    [0, np.cos(y_p), -np.sin(y_p)],
    [-np.sin(x_p), np.cos(x_p) * np.sin(y_p), np.cos(x_p) * np.cos(y_p)]
])
print("\n", "Rp = ", Rp)
Rp_RpT = np.dot(Rp, Rp.T)
RpT_Rp = np.dot(Rp.T, Rp)
if np.allclose(Rp_RpT, np.eye(3)) and np.allclose(RpT_Rp, np.eye(3)):
    print("Matrix Rp is orthogonal.")
else:
    print("Matrix Rp is not orthogonal.")

R = np.dot(np.dot(np.dot(Rp, R_3), N), P)
print("\n", "R = ", R)
R_RT = np.dot(R, R.T)
RT_R = np.dot(R.T, R)

if np.allclose(R_RT, np.eye(3)) and np.allclose(RT_R, np.eye(3)):
    print("Matrix R is orthogonal.")
else:
    print("Matrix R is not orthogonal.")


GAST =  0.0755480996647291 rad
x_p =  -2.2592317539704379e-07 rad
y_p =  2.1288168737519725e-06 rad

 R_3 =  [[ 0.9971476   0.07547625  0.        ]
 [-0.07547625  0.9971476   0.        ]
 [ 0.          0.          1.        ]]
Matrix R_3 is orthogonal.

 Rp =  [[ 1.00000000e+00 -4.80949068e-13 -2.25923175e-07]
 [ 0.00000000e+00  1.00000000e+00 -2.12881687e-06]
 [ 2.25923175e-07  2.12881687e-06  1.00000000e+00]]
Matrix Rp is orthogonal.

 R =  [[ 9.97161620e-01  7.52907475e-02 -8.02800823e-05]
 [-7.52907468e-02  9.97161623e-01  1.22225593e-05]
 [ 8.09724629e-05 -6.14351966e-06  9.99999997e-01]]
Matrix R is orthogonal.



---
g. compute the coordinates of the satellite in $ITRF, (X,Y,Z)_{ITRS}$
$$
\begin{bmatrix}
x_{ITRF} \\
y_{ITRF} \\
z_{ITRF} \\
\end{bmatrix} = R

\begin{bmatrix}
x \\
y \\
z \\
\end{bmatrix}
$$

In [70]:
[[x], [y], [z]] = np.dot(R, np.array([[X], [Y], [Z]]))

print("x = ", round(x, 9), "m")
print("y = ", round(y, 9), "m")
print("z = ", round(z, 9), "m")

x =  13067963.096008142 m
y =  3198732.10315171 m
z =  22670874.615909804 m



---
h. compare the geocentric distance to satellite, $r = \sqrt{X^2 + Y^2 + Z^2}$, computed in $ICRF$ and $ITRF$ respectively.

$$
r_{ICRF} = \sqrt{X^2 + Y^2 + Z^2} \\
r_{ITRF} = \sqrt{x_{ITRF}^2 + y_{ITRF}^2 + z_{ITRF}^2} \\






In [71]:
r_ICRF = np.sqrt(X ** 2 + Y ** 2 + Z ** 2)
print("r_ICRF = ", round(r_ICRF, 8), "m")
r_ITRF = np.sqrt(x ** 2 + y ** 2 + z ** 2)
print("r_ITRF = ", round(r_ITRF, 8), "m")
print("Δr = ", r_ITRF - r_ICRF, "m")
a = 5 + 1


r_ICRF =  26362323.5394126 m
r_ITRF =  26362323.5394126 m
Δr =  0.0 m
